### PR TITLE
build: Specify the C libsodium dep properly

### PR DESCRIPTION
**Pull request by kirelagin**
## Description

Fix build on Linux by correctly specific the dependency on the libsodium
C library.

[//]: # (Here you can add a link to the corresponding issue tracker, e. g. https://issues.serokell.io/issue/SDAO-)

#### Related changes (conditional)

- Tests
  - [x] If I added new functionality, I added tests covering it.
  - [x] If I fixed a bug, I added a regression test to prevent the bug from
        silently reappearing again.

- Documentation
  - [x] I checked whether I should update the docs and did so if necessary:
    - [README](../tree/master/README.md)
    - Haddock

- Public contracts
  - [x] Any modifications of public contracts comply with the [Evolution
  of Public Contracts](https://www.notion.so/serokell/Evolution-of-Public-Contracts-2a3bf7971abe4806a24f63c84e7076c5) policy.
  - [x] I added an entry to the [changelog](../tree/master/CHANGES.md) if my changes are visible to the users
        and
  - [x] provided a migration guide for breaking changes if possible

#### Stylistic guide (mandatory)

- [x] My commits comply with [the policy used in Serokell](https://www.notion.so/serokell/Where-and-how-to-commit-your-work-58f8973a4b3142c8abbd2e6fd5b3a08e).
- [x] My code complies with the [style guide](../tree/master/docs/code-style.md).

### CODE REVIEW

**Comment by gpevnev** [comment]
I though I fixed shell problems in https://github.com/serokell/staker-dao/commit/2caed3853d057c08d7aa45b0c4d88add9cb54b7b. For me nix-build worked even before the fix in this commit propblem was just in shell.

**Comment by awson** [comment]
I never tried this on Windows, but it is definitely better to not depend on `pkg-config` on Windows and on non-nix Linux/MacOS too.

Regarding `nix` I'm not competent enough to argue on this. If the nix way to handle extra libs is using  `pkg-config`, then it's OK to make this change.

**Comment by gpevnev** [comment]
Why do we need to use `pkg-config` and not link directly against `libsodium` as in current master. (at least as I understand)

**Comment by kirelagin** [comment]
pkg-config is _the standard_ way of discovering C dependencies on non-Windows (I think it also kinda works on Windows, but I’m not sure). It is essentially _the only_ way to discover dependencies, if they happen to be in non-standard locations. It makes sure that all paths (e.g. to include headers and the library files) will be setup correctly and, in addition, makes sure auxiliary linking flags are correct. Please, see [`pkgconfig-depends`](https://www.haskell.org/cabal/users-guide/developing-packages.html#pkg-field-pkgconfig-depends) for details.

**Comment by kirelagin** [comment]
> I though I fixed shell problems

It’s not a problem with shell, it’s a problem with haskell.nix. The issue, basically, is that haskell.nix is trying to make sure that all C dependencies are present and tries to install `pkgs.sodium`, but the library is called `pkgs.libsodium`. I’m not sure if it would make sense to add to haskell.nix logic that would try to stick `lib` in front of the package name when looking for it... maybe that might be a viable strategy, but in this specific case `libsodium` supports pkg-config, so there is absolutely no reason not to use it.

**Comment by kirelagin** [comment]
> This is `cabal2nix` generated on current master without these changes and it looks like it handles libsodium properly.

`cabal2nix` is terrible. In this specific case it works because it has a huge stupid map of library names: https://github.com/NixOS/cabal2nix/blob/b942b6aedd11852f6dc995bea944ca1c39ccc200/src/Distribution/Nixpkgs/Haskell/FromCabal/Name.hs#L146.

**Comment by awson** [comment]
Long story short, `pkgconfig` is shitty as hell on Windows.

`pkgconfig` itself is just another package discoverability system, which, like all such systems maintains "garbage in — garbage out" invariant.

I saw a lot of horribly broken `.pc` files, ridden with wrong paths, wrong options etc, and even if I fix them manually, the next package update writes buggy config file over again. Just another source of pain.

So for many years already when I face such a problem (on Windows `pkgconfig` almost *never* works) I usually fix native build system (`cabal`, `opam` etc) config file to remove `pkgconfig`-related stuff altogether.

Honestly, I missed the moment when `pkgconfig` grew out from a niche `gtk`-related tool (I believe some 6-7 years ago almost no packages outside of `gtk` suite of libs used it) to "the standard" one.

**Comment by awson** [comment]
> 
> 
> `cabal2nix` is terrible. In this specific case it works because it has a huge stupid map of library names: https://github.com/NixOS/cabal2nix/blob/b942b6aedd11852f6dc995bea944ca1c39ccc200/src/Distribution/Nixpkgs/Haskell/FromCabal/Name.hs#L146.

Btw, *any* working config system has a lot of such "stupid" hardcoded things.

And even more: such "stupid" hardcoded things is almost *the only value* such a system in fact provides.

**Pull request merged**
